### ISSUE TITLE
babel-eslint is deprecated

### ISSUE THREAD

**Issue by rinu** [vuejs/vue-eslint-parser#101]
Accoring to https://www.npmjs.com/package/babel-eslint
Please replace the deprecated dependency with the new one.

**Comment by ota-meshi** [comment]
We still need to use babel-eslint as the new parser does not support older Node versions.

**Comment by tenkiller** [comment]
Shouldn't the correct long-term solution be to no longer support older Node versions?

**Comment by ota-meshi** [comment]
Perhaps the next major version upgrade will drop supporting older node.  But now we have no plans to do so.
