### ISSUE TITLE
Do you have plan to support "?."

### ISSUE THREAD

**Issue by muxishuihan** [vuejs/vue-eslint-parser#106]
Hi~ 
It seems there is some operation in vue that vue-eslint-parser doesn't support, such as "?."
`let arr = res?.data?.list`
it equals to :
`let arr = res && res.data && res.data.list`
I would like to know do you have some plan to support "?." 
Best wishes

**Comment by ota-meshi** [comment]
vue-eslint-parser can parse optional chaining. It works fine in the test case. Perhaps you have the wrong settings or are using an older version.

https://github.com/vuejs/eslint-plugin-vue/blob/master/tests/fixtures/script-indent/optional-chaining-03.vue
