### ISSUE TITLE
Maybe a breaking change

### ISSUE THREAD

**Issue by wjq990112** [vuejs/vue-eslint-parser#112]
dependence `espree` is a breaking change, which is only support node version `>= 12`.

**Comment by ota-meshi** [comment]
When used with ESLint, it does not actually use the dependent espree. So I thought it wasn't a breaking change, but isn't it?

**Comment by Benoit-Vasseur** [comment]
`vue create` seems broken because of espressV8 => https://github.com/vuejs/vue-cli/issues/6562#issuecomment-872838355 (depending of the node version you have). So it has some impact ^^

**Comment by wjq990112** [comment]
> When used with ESLint, it does not actually use the dependent espree. So I thought it wasn't a breaking change, but isn't it?

It will fail when `npm install`, because of node version.

**Comment by sodatea** [comment]
Yarn treats the `engines` field very strictly, so Yarn users with old Node.js versions will be affected.

So technically, we need a semver major bump for the change.

But please, update your Node version in this case…
Node.js 10 has reached End-of-Life long ago.

**Comment by sodatea** [comment]
> It will fail when `npm install`, because of node version.

It won't. `engine-strict` defaults to false in NPM.
https://docs.npmjs.com/cli/v7/using-npm/config#engine-strict

**Comment by wjq990112** [comment]
> It won't. `engine-strict` defaults to false in NPM.
> https://docs.npmjs.com/cli/v7/using-npm/config#engine-strict

Sorry, mistyped, it will fail when `yarn install`.

**Comment by Benoit-Vasseur** [comment]
The engine requirements of espreeV8 is very strict : `Expected version "^12.22.0 || ^14.17.0 || >=16.0.0"` 

So it fails if you use yarn and node v12.21 or 14.16.0 for exemple :/

**Comment by Benoit-Vasseur** [comment]
The engine requirements of espreeV8 is very strict : `Expected version "^12.22.0 || ^14.17.0 || >=16.0.0"` 

So it fails if you use yarn and node v12.21 or 14.16.0 for exemple :/

**Comment by sodatea** [comment]
Workaround:

Create a `.yarnrc` file in the project root, with the following content:
```
--install.ignore-engines true
```

**Comment by wjq990112** [comment]
But in this package:

engines version is
```json
"engines": {
  "node": ">=8.10"
},
```

but dependence `espree` is `^12.22.0 || ^14.17.0 || >=16.0.0`.

Is that correct?

**Comment by ota-meshi** [comment]
I make a fix that downgrades the espree dependency.
