### ISSUE TITLE
Parsing error: Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by fanfanTD** [vuejs/vue-eslint-parser#147]
issues: @vue/eslint-config-standard & vue-eslint-parser@7.11.0

Hi, I'm using @vue/eslint-config-standard  in my project. When install  eslint-plugin-vue: ^7.0.0, which is based on vue-eslint-parser@7.11.0, I find there're both babel-eslint (obsolete , lead to fail of installation) and @babel/eslint-parser in package.json. So i can't use the lastest version of @vue/eslint-config-standard.

Possible solutions:
   1. Delete the babel-eslint in vue-eslint-parser@7.11.0.

**Comment by ota-meshi** [comment]
vue-eslint-parser has no babel-eslint dependency. The same is true for v7.11.0.

https://github.com/vuejs/vue-eslint-parser/blob/v7.11.0/package.json#L12-L23

**Comment by LinusBorg** [comment]
@ota-meshi well, it's in devDependencies at least.
