### ISSUE TITLE
vue-eslint-parser + @typescript-eslint/parser inside <template>

### ISSUE THREAD

**Issue by ilyub** [vuejs/vue-eslint-parser#163]
I am adapting my typescript eslint rules to work inside .vue components.
I found that "context.parser.esTreeNodeToTSNodeMap.get" works fine inside <script lang="ts"> section.
But inside <template> section it returns undefined.

[Vue documentation](https://vuejs.org/guide/typescript/overview.html#usage-in-single-file-components) says:
"When lang="ts" is present, all template expressions also enjoy stricter type checking."
So, I guess it is not vue problem.

Does it mean that vue-eslint-parser ignores @typescript-eslint/parser inside <template> section and is there any chance to fix this?

**Comment by ota-meshi** [comment]
This parser cannot be used to retrieve type information within a `<template>`. To do that, you need to write a new parser.
