### ISSUE TITLE
Program:exit called before Vue nodes

### ISSUE THREAD

**Issue by ilyub** [vuejs/vue-eslint-parser#164]
It looks like a common pattern to collect info from multiple nodes and do final check in "Program:exit".
However, this pattern breaks for Vue nodes (e.g. VElement), because Vue nodes are called after "Program:exit".
I think this is not right because Program is the topmost node:
![image](https://user-images.githubusercontent.com/70687432/183102796-d42f28e8-f96f-4c93-b903-d57536570aa0.png)

Using "VElement[name=template]:exit" does not solve the problem because <template> section is not always present 

Is it possible to fix it? I.e. to visit template section before Program:exit?

**Comment by ota-meshi** [comment]
> Is it possible to fix it? 

No. it cannot be changed. This is because we are traversing the template nodes in the `Program:exit` listener.
