### ISSUE TITLE
After upgrade it displays "can't resolve reference #/definitions/directiveConfigSchema from id #"

### ISSUE THREAD

**Issue by crystalfp** [vuejs/vue-eslint-parser#166]
Maybe the behavior descripted in  [#16232](https://github.com/eslint/eslint/issues/16232#issue-1348130574) is a problem for this parser and not of general eslint.

**Comment by ota-meshi** [comment]
It looks to me like it's not a parser issue.

https://github.com/eslint/eslint/issues/16232#issuecomment-1224253445
