### ISSUE TITLE
parser doesn't infer ecmaVersion from env

### ISSUE THREAD

**Issue by jonaskuske** [vuejs/vue-eslint-parser#168]
When using eslint with its default parser, it is enough to specify the ECMA Version as part of the env, as it also sets `parserOptions.ecmaVersion`. For example, `"env": { "ecma2022": true }` automatically sets `parserOptions.ecmaVersion` to `13`. This is explained in the official ESLint docs: https://eslint.org/docs/latest/user-guide/configuring/language-options#specifying-environments

When using the Vue parser that behavior does not exist, you have to set `parserOptions.ecmaVersion` manually.

**Comment by ota-meshi** [comment]
Could you please provide a minimal repository to reproduce issue?

**Comment by jonaskuske** [comment]
closed in favor of https://github.com/vuejs/eslint-plugin-vue/issues/1991 :)
