### ISSUE TITLE
Support for import assertions

### ISSUE THREAD

**Issue by frankykubo** [vuejs/vue-eslint-parser#175]
I would like to ask, if there is plan to implement support for import assertions. I want to dynamically import json like this:

```
const testVar = await import('./test.json', { assert: { type: 'json' } });
```

but I am obviously getting error:
```
[@vue/compiler-sfc] This experimental syntax requires enabling the parser plugin: "importAssertions". (27:73)
```
@babel/eslint-parser already has the support of it, as the solutions on [stackoverflow](https://stackoverflow.com/questions/72067118/how-to-enable-import-assertions-for-babel)  are recommending of using it.

Thank you.

**Comment by ota-meshi** [comment]
Use a parser that supports import assertions for parserOptions.parser. vue-eslint-parser doesn't handle that.
