### ISSUE TITLE
[Feature request] Support custom macros

### ISSUE THREAD

**Issue by matthew-dean** [vuejs/vue-eslint-parser#180]
It seems that this parser supports the `defineProps` and `defineEmits` macros by default. Would it be possible to add support for [this custom macro library](https://vue-macros.sxzz.moe/guide/configurations.html)?

**Comment by ota-meshi** [comment]
We have no plans to support features outside of the Vue official (and Nuxt official) libraries.

I think you can use global configuration to allow those macros.
https://eslint.org/docs/latest/use/configure/language-options#specifying-globals
