### ISSUE TITLE
How to apply different rules for sfc file based on script tag "lang"

### ISSUE THREAD

**Issue by languanghao** [vuejs/vue-eslint-parser#185]
I want to migrate my project from vue2 (sfc with javascript) to vue3 (sfc with typescript), but vue sfc file only apply rules under `*.vue`.

Is it possible to config eslint use different rules by `<script lang='js/ts'>`?

**Comment by ota-meshi** [comment]
We cannot configure rules per lang attribute.

If you really want to do that, you'll have to use a trick to parse and configure each file yourself.
https://github.com/sveltejs/eslint-plugin-svelte/issues/152#issuecomment-1150803175
