### ISSUE TITLE
Bug: Parsing error: Cannot set property index of Error which has only a getter

### ISSUE THREAD

**Issue by zWingz** [vuejs/vue-eslint-parser#206]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I'm using [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue).
- [X] I'm sure the problem is a parser problem. (If you are not sure, search for the issue in [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) repo and open the issue in [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) repo if there is no solution.
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

latest

### What version of `eslint-plugin-vue` and ` vue-eslint-parser` are you using?

- vue-eslint-parser@latest
- eslint-plugin-vue@latest

### What did you do?

<details>
<summary>Configuration</summary>

### ESLint Config

```javascript
module.exports = {
  extends: [
    // add more generic rulesets here, such as:
    'eslint:recommended',
  ],
  parser: 'vue-eslint-parser',
  parserOptions: {
    parser: '@typescript-eslint/parser',
    ecmaVersion: 6,
    extraFileExtensions: ['.vue'],
    ecmaFeatures: {
      jsx: true,
    },
    project: true, // will work if disable this line
  },
  plugins: ['@typescript-eslint'],
}
```

### tsconfig

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "es6",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "lib": ["esnext", "dom"],
  },
  "include": [
    "."
  ],
  "exclude": ["node_modules"]
}
```

App
```vue
<template>
  <div>1</div>
</template>
<script lang="tsx">
import { defineComponent } from 'vue'
  const test = 1;
    const b = 2;
      const test = defineComponent({
        props: {
          test: String,
        },
        render() {
          return <div>test</div>
        }
      })
</script>
```

</details>

### What did you expect to happen?

<img width="604" alt="image" src="https://github.com/typescript-eslint/typescript-eslint/assets/13031838/b8de9d7e-b283-4ab2-aa6b-7d3f6dcf2499">

### What actually happened?

<img width="675" alt="image" src="https://github.com/typescript-eslint/typescript-eslint/assets/13031838/432dcaed-310a-4b19-ba11-9668f843cbd0">

### Link to Minimal Reproducible Example

https://github.com/zWingz/test-vue-eslint

### Additional comments

enable or disable the `project: true`

<img width="1567" alt="image" src="https://github.com/typescript-eslint/typescript-eslint/assets/13031838/68e7e568-9f9d-4b0d-a7b1-32d10f224d85">

<img width="1562" alt="image" src="https://github.com/typescript-eslint/typescript-eslint/assets/13031838/8ded7759-b1d2-44b6-8303-bba1c8a8b6be">

**Comment by zWingz** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/7597

**Comment by k713927** [comment]
me too ,how to do

**Comment by ernestoalejo** [comment]
Downgrading to v9.2.1 removes the bug but misses out on important things like the integration with generic Vue 3.3 components.

```shell
npm i -D vue-eslint-parser@v9.2.1
```

**Comment by zWingz** [comment]
> Downgrading to v9.2.1 removes the bug but misses out on important things like the integration with generic Vue 3.3 components.
> 
> ```shell
> npm i -D vue-eslint-parser@v9.2.1
> ```

still no work

**Comment by PaulCEllsworth** [comment]
> > Downgrading to v9.2.1 removes the bug but misses out on important things like the integration with generic Vue 3.3 components.
> > ```shell
> > npm i -D vue-eslint-parser@v9.2.1
> > ```
> 
> still no work

Same here (Windows 10, pnpm, node@18.15.0, vue@3.3.4)
