### ISSUE TITLE
Support for Vue.js 3.4

### ISSUE THREAD

**Issue by ota-meshi** [vuejs/vue-eslint-parser#212]
- [ ] v-bind shorthand for key and value with the same name (added in v3.4.0-alpha.2)
- [x] defineModel()

**Comment by ota-meshi** [comment]
related to https://github.com/vuejs/eslint-plugin-vue/issues/2326

**Comment by grandsong** [comment]
I want "v-bind shorthand" very much! I'm looking forward to this support!

**Comment by bodograumann** [comment]
Will this solve "defined but never used" errors in the following examples?

**v-slot**
```
<router-link custom v-slot="{ href }">
  <a :href>
</router-link>
```

triggers `unused-imports/no-unused-vars`.

**v-for**
```
<div v-for="(label, idx) of items" :key="idx">
  <MyButton :label />
</div>
```

triggers `vue/no-unused-vars`.

**data**
```
<template>
  <MyButton :label />
</template>

<script setup>
const label = "some text";
</script>
```

triggers `vue/no-unused-vars`.
