### ISSUE TITLE
If there are two <script>tag, only the first one will be parsed.

### ISSUE THREAD

**Issue by jenkey2011** [vuejs/vue-eslint-parser#58]
## question
In some cases, a file may have two `<script>` tags, bug only the first one will be parsed.

exp:
```vue
<template>
  <div />
</template>

<script type="customBlock">
// The code here will be normally parsed
let a = 1
</script>

<script>
export default {
  //  The code here will be ignored
   let b = 2
}
</script>
```

![image](https://user-images.githubusercontent.com/20010737/64935165-29ca9080-d882-11e9-9c5e-25e2e0b521c7.png)

## Expect
Parse all code, or we can customize parsing of certain code libraries.

**Comment by ota-meshi** [comment]
I don't think you can use more than one script tag in Vue's SFC (except for experimental features). So I don't think it's necessary to support more than one script tag.

Why do you want this?

**Comment by ota-meshi** [comment]
I have no plans to support multiple scripts other than `<script setup>`, so I will close this issue.

**Comment by sevilyilmaz** [comment]
It's not an edge case for Vue 3 to have multiple `script` tags. There are even suggestions of its usage [here](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md#usage-alongside-normal-script) and [here](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md#declaring-additional-options).

@ota-meshi could you reconsider adding the support?

**Comment by ota-meshi** [comment]
Yes. Using `<script>` with `<script setup>` is already supported.

**Comment by sevilyilmaz** [comment]
I got an error when I added `<script>` after `<script setup>` but the error got disappeared when I changed the order and put `<script>` above.

**Comment by uyarn** [comment]
> I got an error when I added `<script>` after `<script setup>` but the error got disappeared when I changed the order and put `<script>` above.

exactly, but it's a conflict with the rule `import/first` >.<
