### ISSUE TITLE
Possible to parse/expose <style> section?

### ISSUE THREAD

**Issue by jmoore914** [vuejs/vue-eslint-parser#63]
As of now, the parser only exposes the AST for the <template> section of SFCs. Would it be possible to also parse the <style> section to allow for additional linting? It looks like @future-architect was able to make it work here: https://github.com/future-architect/eslint-plugin-vue-scoped-css

**Comment by ota-meshi** [comment]
I also maintain eslint-plugin-vue-scoped-css, but I'm not going to support CSS in this parser. So I close this issue.
