### ISSUE TITLE
Supports for <script setup> and <style> variable injection

### ISSUE THREAD

**Issue by ota-meshi** [vuejs/vue-eslint-parser#78]
Vue.js 3.0 is about to include [<script setup>] and [<style vars>] as experimental features. (refer to https://github.com/vuejs/rfcs/issues/189)

It seems that can write script like function arguments in `<script setup="...">` and script like object expression in `<style vars="...">`. 

Can vue-eslint-parser be changed to support these parsers?

~~If the parser supports these parses then, I have one more question to ask.  
Perhaps the arguments given to [<script setup>] will need to be registered with the scope manager as global variables.  
Should the parser register this global variable? Or is it okay if the `vue/experimental-script-setup-vars` rules etc. register (and remove from `through`) global variables?~~

---

EIDT:

- `<style>` may not need to be parsed.
https://github.com/vuejs/rfcs/pull/231

- `<script setup="...">` may not need to be parsed.
However, multiple `<script>` blocks must be parsed as a single script.
https://github.com/vuejs/rfcs/pull/227

---

Related to https://github.com/vuejs/eslint-plugin-vue/issues/1248.

[<script setup>]: https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-script-setup.md
[<style vars>]: https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-style-variables.md

**Comment by aggmoulik** [comment]
Do anyone working on this issue ?

**Comment by ota-meshi** [comment]
Hi @aggmoulik.
No one is working because we haven't yet discussed how to change it.

**Comment by aggmoulik** [comment]
Okay, So let's do that discussion.

**Comment by MartinMa** [comment]
I have no idea how any of this works, but my eslint setup throws `no-unused-vars` errors when using the new experimental `<script setup>` syntax. Any idea how I can work around that? Should I disable the `no-unused-vars` rule for now or better stick to the more verbose setup syntax? The VS Code extension Volar already supports the new syntax with IntelliSense in the template block.

**Comment by ota-meshi** [comment]
The RFC hasn't been merged yet, so I'm not thinking about the details.
Currently, you need to turn off the `no-unused-vars` rule for `<script setup>`.
If you create a special ESLint rule, use `markVariableAsUsed` to mark the variables. https://eslint.org/docs/developer-guide/working-with-rules#the-context-object
